version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"  # Map port 8080 on the host to port 5000 in the container
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]